version: '3.3'

services:
  DIGItronik-app:
    container_name: DIGItronik
    image: digi-tronik:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://DIGItronik-mongo:27017/digitronik-db
    depends_on:
      - DIGItronik-mongo
      
  DIGItronik-mongo:
    container_name: DIGItronik-mongo
    image: mongo:latest
    restart: always
    hostname: host-mongo 
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: digitronik-db
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb
  
  # DIGItronik-frontend:
  #   container_name: DIGItronik-frontend
  #   image: digi-tronik-frontend:1.0
  #   build: frontend
  #   ports:
  #     - "4200:4200"